### ISSUE TITLE
Improve code

### ISSUE THREAD

**Issue by va6996** [va6996/Autograder#5]
All functions have been static which is not a good practice. Change the code to use non-static functions.

**Comment by jpitchardu** [comment]
Bro that implies re-designing the classes.

**Comment by wadleo** [comment]
Hey @va6996 @pichardoSoftware, I would love to contribute to this project but there is no readme, so I'm kind of lost. But I'm looking in to the code, though the readme could have made contributing a lot easier. I'm currently looking in to this issue.

**Comment by va6996** [comment]
@wadleo , will add a readme asap!

**Comment by wadleo** [comment]
:+1:
